### ISSUE TITLE
Shuffling does not change DOM order

### ISSUE THREAD

**Issue by bnadji** [Vestride/Shuffle#296] opened 2019-10-08 18:06 UTC
Have a simple group of five `<div>`,` id=div1, ... div5`.  After shuffling them, even though div1 through div5 appear shuffled on the screen, e.g., div2, div1, div4, div5, div3, the DOM object still has them in the same original order of, `div1, div2, ... div5`.  The question is that if there is a way to tell Shuffle to sync the DOM with the actual screen representation of the shuffled group?  

This is required for the applications that need to further manipulate the DOM and have to have an accurate representation of what is on the screen in the DOM.

**Comment by Vestride** [comment] 2020-01-31 07:10
duplicate of #175

**Closed by Vestride** 2020-01-31 07:10 UTC
